; THIS IS A SAMPLE platformio.ini FILE FOR PEOPLE WHO DO NOT USE build.sh TO MANAGE THE BUILD, AND
; WISH INSTEAD TO USE VSCODE PLUGIN.
; IF YOU WANT THE LATEST SUPPORTED VERSION OF CONFIGURATION WHEN IT
; IS ADDED TO THE CODEBASE, USE build.sh INSTEAD.
; IF YOU CHOOSE TO CRAFT YOUR OWN PLATFORMIO.INI FILE, YOU WILL HAVE TO MANUALLY EDIT IT FOR ANY CHANGES TO THE GLOBAL CONFIGURATION THAT ARE INTRODUCED
; E.G. PLATFORM VERSION, NEW PYTHON SCRIPTS ETC.
;
;FujiNet PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[fujinet]
; Espressif32 PlatformIO Version to use for building
;esp32_platform_version = 3.2.0 ; For Bluetooth support
;esp32_platform_version = 3.4.0 ; old stable
;esp32_platform_version = 6.3.2 ; last stable
esp32_platform_version = 6.10.0 ; latest
esp32_platform_packages = 
;    toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 ; required for platform version < 5.3.0, remove this line when upgrading to the >=5.3.0
esp32s3_platform_version = 6.10.0
esp32s3_platform_packages =

; Choose SPIFFS or LITTLEFS for the filesystem used on internal flash
; NOTE: SPIFFS adds startup overhead causing some systems not to boot without pre-powering via external
; flash_filesystem = FLASH_SPIFFS 
flash_filesystem = FLASH_LITTLEFS

; Override platform name when creating firmware ZIP file
; ex: fujinet-CUSTOMNAME-v1.0.zip
;platform_name = CUSTOMNAME

; Uncomment the platform, bus and board type you are building for below
;build_platform = BUILD_RS232
;build_bus      = rs232
;build_board    = fujinet-rs232-rev0      ; RS232 Rev0 Prototype Carrier
;build_board    = fujinet-rs232-s3        ; RS232 ESP32S3
;build_board    = fujinet-rs232-s3-palm   ; RS232 ESP32S3, Palm HotSync cradle defaults
;build_board    = fujiversal-rs232        ; Fujiversal RS232 ESP32S3

[platformio]
description = FujiNet retro computer to ESP32 WiFi Multifunction Firmware
default_envs = ${fujinet.build_board}
data_dir = ./data/${fujinet.build_platform}

[env]
; Common settings for all enivornments
framework = espidf
extra_scripts =
    pre:build_packages.py
    pre:build_version.py
    pre:build_webui.py
;    post:build_firmwarezip.py ; Optional, build firmware ZIP file for flash tool
lib_ldf_mode = off ; off chain deep chain+ deep+
upload_speed = 460800 ;921600
;upload_port = COM1 ; Windows
upload_port = /dev/ttyUSB0 ; Linux/WSL
;upload_port = /dev/ttyACM0 ; Linux esp32s3
;upload_port = /dev/tty.SLAB_USBtoUART ; Mac
monitor_speed = 460800 ;921600
;monitor_speed = 115200 ; esp32s3
;monitor_port = COM1 ; Windows
monitor_port = /dev/ttyUSB0 ; Linux/WSL
;monitor_port = /dev/ttyACM0 ; Linux esp32s3
;monitor_port = /dev/tty.SLAB_USBtoUART ; Mac
monitor_filters = esp32_exception_decoder, time ;,log2file
check_skip_packages = yes ; so that check will work.
board_build.filesystem = littlefs

build_flags =
    -D ${fujinet.build_platform}
    -D ${fujinet.flash_filesystem}
    -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
    -D DEBUG_SPEED=${env.monitor_speed}
    ; Make the SPI SD CRC-enable step (CMD59) non-fatal - see __wrap_sdmmc_init_spi_crc()
    ; in lib/FileSystem/fnFsSD.cpp
    -Wl,--wrap=sdmmc_init_spi_crc
    ;-D LEAK_DEBUG           ; Show low heap usage every service loop.
    ;-D NO_BUTTONS          ; if your hardware has no physical buttons
    ;-D JTAG                ; enable use with JTAG debugger
    ;-D BLUETOOTH_SUPPORT   ; enable BlueTooth support
    ;-D VERBOSE_PROTCOL     ;
    ;-D VERBOSE_TNFS        ;
    ;-D VERBOSE_DISK        ;
    ;-D VERBOSE_HTTP        ;
    ;-D DBUG2               ; enable monitor messages for a release build
    ;-D ENABLE_CONSOLE      ; enable console
    ;-D ENABLE_DISPLAY      ; enable display

; FujiNet RS232 Rev 0 Prototype (ESP32-DEVKITC-VE 8MB Flash, 8MB PSRAM)
[env:fujinet-rs232-rev0]
platform = espressif32@${fujinet.esp32_platform_version}
platform_packages = ${fujinet.esp32_platform_packages}
board = fujinet-v1-8mb
build_type = debug
build_flags =
    ${env.build_flags}
    -D PINMAP_RS232_REV0

; FujiNet RS232 Rev1 Prototype (ESP32S3 WROOM 16MB Flash, 8MB PSRAM)
[env:fujinet-rs232-s3]
platform = espressif32@${fujinet.esp32s3_platform_version}
platform_packages = ${fujinet.esp32s3_platform_packages}
board = esp32-s3-wroom-1-n16r8
build_type = debug
build_flags =
    ${env.build_flags}
    -fexceptions
    -D PINMAP_RS232_S3
    -D DEBUG_ON_CDC         ; Send debug output over USB CDC device instead of secondary USB UART
    -D USB_HOST_DEBUG       ; Debug messages for ESP32S3 USB Host
build_unflags = -fno-exceptions
board_build.cmake_extra_args = -D CONFIG_IDF_TARGET_ESP32S3=1 ; extra arguments for CMake
upload_port = /dev/ttyACM0 ; Linux esp32s3
monitor_port = /dev/ttyACM0 ; Linux esp32s3
